# Generated by Django 5.1.2 on 2024-10-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Название')),
                ('course_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='education/image/', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Название')),
                ('lesson_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('lesson_image', models.ImageField(blank=True, null=True, upload_to='education/image/', verbose_name='превью')),
                ('lesson_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
